# Generated by Django 4.2.3 on 2023-07-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_dt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_dt',
            new_name='updated_at',
        ),
    ]
